#all.score
	acur<-data.frame(acura.scores)
	bentle<-data.frame(bentley.scores)	
	ben<-data.frame(benz.scores)
	bm<-data.frame(bmw.scores)
	buic<-data.frame(buick.scores)
	cadilla<-data.frame(cadillac.scores)
	chrysle<-data.frame(chrysler.scores)
	dodg<-data.frame(dodge.scores)
	fia<-data.frame(fiat.scores)
	fiske<-data.frame(fisker.scores)
	gm<-data.frame(gmc.scores)
	hond<-data.frame(honda.scores)
	hyunda<-data.frame(hyundai.scores)
	infinit<-data.frame(infiniti.scores)
	jagua<-data.frame(jaguar.scores)
	jee<-data.frame(jeep.scores)
	lamb<-data.frame(lambo.scores)
	landrove<-data.frame(landrover.scores)
	lexu<-data.frame(lexus.scores)
	lotu<-data.frame(lotus.scores)
	mazd<-data.frame(mazda.scores)
	min<-data.frame(mini.scores)
	mitsubish<-data.frame(mitsubishi.scores)
	nissa<-data.frame(nissan.scores)
	ramtruc<-data.frame(ramtruck.scores)
	roll<-data.frame(rolls.scores)
	scio<-data.frame(scion.scores)
	
#check
	library(sqldf)

	acura<-sqldf("select score,airline from acur")
	bentley<-sqldf("select score,airline from bentle")
	benz<-sqldf("select score,airline from ben")
	bmw<-sqldf("select score,airline from bm")
	buick<-sqldf("select score,airline from buic")
	cadillac<-sqldf("select score,airline from cadilla")
	chrysler<-sqldf("select score,airline from chrysle")
	dodge<-sqldf("select score,airline from dodg")
	fiat<-sqldf("select score,airline from fia")
	fisker<-sqldf("select score,airline from fiske")
	gmc<-sqldf("select score,airline from gm")
	honda<-sqldf("select score,airline from hond")
	hyundai<-sqldf("select score,airline from hyunda")
	infiniti<-sqldf("select score,airline from infinit")
	jaguar<-sqldf("select score,airline from jagua")
	jeep<-sqldf("select score,airline from jee")
	lambo<-sqldf("select score,airline from lamb")
	landrover<-sqldf("select score,airline from landrove")
	lexus<-sqldf("select score,airline from lexu")
	lotus<-sqldf("select score,airline from lotu")
	mazda<-sqldf("select score,airline from mazd")
	mini<-sqldf("select score,airline from min")
	mitsubishi<-sqldf("select score,airline from mitsubish")
	nissan<-sqldf("select score,airline from nissa")
	ramtruck<-sqldf("select score,airline from ramtruc")
	rolls<-sqldf("select score,airline from roll")
	scion<-sqldf("select score,airline from scio")
	
all.scores<-rbind(acura,bentley,benz,bmw,buick,cadillac,chrysler,dodge,
		fiat,fisker,gmc,honda,hyundai,infiniti,jaguar,jeep,lambo,
		landrover,lexus,lotus,mazda,mini,mitsubishi,nissan,ramtruck,
		rolls,scion)

#check